channels: !!python/tuple
  - conda-forge
  - defaults
dependencies:
  - python=3.4
  - cython
  - numpy=1.11
  - pandas
  - pyodbc
  - click
  - pip
  - setuptools
  - wheel
  - sphinx
  - alabaster
  - matplotlib
  - pip:
    - pytest
    - sphinxcontrib-napoleon
